AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: my-queue.fifo
      FifoQueue: true
Outputs:
  QueueUrl:
    Value: !Ref MyQueue